
default:
	g++ -O2 -o qsort_leftmost_original qsort_leftmost_original.cpp
	g++ -O2 -o qsort_leftmost_shorter qsort_leftmost_shorter.cpp
	g++ -O2 -o qsort_leftmost_longer qsort_leftmost_longer.cpp
	g++ -O2 -o qsort_median_original qsort_median_original.cpp
	g++ -O2 -o qsort_median_shorter qsort_median_shorter.cpp
	g++ -O2 -o qsort_median_longer qsort_median_longer.cpp

clean:
	rm qsort_leftmost_original
	rm qsort_leftmost_shorter
	rm qsort_leftmost_longer
	rm qsort_median_original
	rm qsort_median_shorter
	rm qsort_median_longer

run:
	@./qsort_leftmost_original 
	@./qsort_leftmost_shorter
	@./qsort_leftmost_longer
	@./qsort_median_original
	@./qsort_median_shorter
	@./qsort_median_longer
	
	
